frr version 9.1
frr defaults traditional
hostname R2
no ipv6 forwarding
service integrated-vtysh-config
!
interface lo
 ip address 10.0.0.2/32
!
interface eth1
 description to-R1
 ip address 10.0.12.2/24
 ip ospf network point-to-point
!
interface eth2
 description to-R3-eBGP
 ip address 10.0.23.2/24
!
router ospf
 ospf router-id 10.0.0.2
 network 10.0.12.0/24 area 0
 network 10.0.0.2/32 area 0
!
router bgp 65001
 bgp router-id 10.0.0.2
 no bgp ebgp-requires-policy
 neighbor 10.0.23.3 remote-as 65002
 neighbor 10.0.23.3 timers 3 9
 address-family ipv4 unicast
  redistribute ospf
  redistribute connected
  neighbor 10.0.23.3 activate
 exit-address-family
!
line vty
!
