frr version 9.1
frr defaults traditional
hostname R3
no ipv6 forwarding
service integrated-vtysh-config
!
interface lo
 ip address 10.0.0.3/32
!
interface eth2
 description to-R2-eBGP
 ip address 10.0.23.3/24
!
interface eth1
 description to-R4
 ip address 10.0.34.3/24
 ip ospf network point-to-point
!
router ospf
 ospf router-id 10.0.0.3
 network 10.0.34.0/24 area 0
 network 10.0.0.3/32 area 0
!
router bgp 65002
 bgp router-id 10.0.0.3
 no bgp ebgp-requires-policy
 neighbor 10.0.23.2 remote-as 65001
 neighbor 10.0.23.2 timers 3 9
 address-family ipv4 unicast
  redistribute ospf
  redistribute connected
  neighbor 10.0.23.2 activate
 exit-address-family
!
line vty
!
