frr version 9.1
frr defaults traditional
hostname R4
no ipv6 forwarding
service integrated-vtysh-config
!
interface lo
 ip address 10.0.0.4/32
!
interface eth1
 description to-R3
 ip address 10.0.34.4/24
 ip ospf network point-to-point
!
interface eth2
 description to-h2
 ip address 10.4.4.1/24
!
router ospf
 ospf router-id 10.0.0.4
 network 10.0.34.0/24 area 0
 network 10.0.0.4/32 area 0
 network 10.4.4.0/24 area 0
!
line vty
!
