"""Pydantic v2 domain models — the real data IP of Engram.

An Incident is a structured *memory trace* of one troubleshooting session on one
network. The structured fields make retrieval filterable; `embedding_text` makes
it semantically searchable; `outcome` makes failure remembered.
"""

from __future__ import annotations

from datetime import datetime, timezone
from uuid import UUID, uuid4

from pydantic import BaseModel, Field

from engram.domain.enums import Layer, Outcome, Protocol, Scope, Severity


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


# ---------------------------------------------------------------------------
# Incident sub-structures
# ---------------------------------------------------------------------------
class Symptom(BaseModel):
    description: str
    affected_layer: Layer = Layer.UNKNOWN
    protocols: list[Protocol] = Field(default_factory=list)
    scope: Scope = Scope.DEVICE
    signature: str = ""  # normalized signature, e.g. BGP_NEIGHBOR_DOWN
    severity: Severity = Severity.SEV3


class Context(BaseModel):
    devices: list[str] = Field(default_factory=list)
    topology_snapshot: dict | None = None
    topology_hash: str | None = None
    config_fragments: dict[str, str] = Field(default_factory=dict)


class InvestigationStep(BaseModel):
    device: str
    command: str
    raw_output: str
    parsed_output: dict | None = None
    timestamp: datetime = Field(default_factory=_utcnow)


class Resolution(BaseModel):
    root_cause: str = ""
    fix_description: str = ""
    config_diff: str | None = None
    commands_applied: list[str] = Field(default_factory=list)


class OutcomeRecord(BaseModel):
    status: Outcome = Outcome.UNKNOWN
    verification_method: str = ""
    verified: bool = False
    mttr_seconds: int | None = None


# ---------------------------------------------------------------------------
# Incident
# ---------------------------------------------------------------------------
class Incident(BaseModel):
    id: UUID = Field(default_factory=uuid4)
    network_id: str  # tenant — present on EVERY incident, scopes all access
    created_at: datetime = Field(default_factory=_utcnow)
    updated_at: datetime = Field(default_factory=_utcnow)
    occurred_at: datetime = Field(default_factory=_utcnow)
    handled_by: str = ""
    title: str = ""
    tags: list[str] = Field(default_factory=list)

    symptom: Symptom
    context: Context = Field(default_factory=Context)
    investigation: list[InvestigationStep] = Field(default_factory=list)
    resolution: Resolution = Field(default_factory=Resolution)
    outcome: OutcomeRecord = Field(default_factory=OutcomeRecord)

    embedding_text: str = ""  # generated by summary.py if not supplied
    embedding_model: str = ""


# ---------------------------------------------------------------------------
# Query + retrieval results
# ---------------------------------------------------------------------------
class FaultQuery(BaseModel):
    """An incoming, in-progress fault to reason about."""

    network_id: str  # set from auth, not trusted from the body
    description: str
    affected_layer: Layer | None = None
    protocols: list[Protocol] = Field(default_factory=list)
    scope: Scope | None = None
    severity: Severity | None = None  # optional; enables severity-proximity scoring
    devices: list[str] = Field(default_factory=list)
    signature: str | None = None
    current_topology_hash: str | None = None


class RetrievedIncident(BaseModel):
    incident: Incident
    vector_score: float
    structured_score: float
    final_score: float
    match_explanation: str
    staleness: dict  # {age_days:int, topology_changed:bool, stale:bool}
    outcome_flag: str | None = None  # e.g. "PRIOR FIX FAILED — do not repeat"


# ---------------------------------------------------------------------------
# Reasoning output (strict JSON contract)
# ---------------------------------------------------------------------------
class IncidentComparison(BaseModel):
    incident_id: str
    similarity_pct: int
    rationale: str
    key_differences: list[str] = Field(default_factory=list)


class ReasoningResult(BaseModel):
    comparisons: list[IncidentComparison] = Field(default_factory=list)
    recommended_hypothesis: str
    recommended_fix: str
    adapted_from: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    confidence: str = "low"  # low | medium | high
    requires_human_approval: bool = True  # always — decision support, never autopilot
